# This workflow will initiate a Veracode Static Analysis Pipeline scan, return a results.json and convert to SARIF for upload as a code scanning alert

name: Veracode Static Analysis Pipeline Scan

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: push
        
        jobs:
        build:
        runs-on: ubuntu-latest
        steps:
        - name: build
        run: maven clean verify
        pipeline-scan:
        runs-on: ubuntu-latest
        steps:
        - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
        java-version: 1.8
        - name: Download the Pipeline Scanner
        uses: wei/curl@master
        with:
        args: -O https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
        - name: Unzip the Pipeline Scanner
        run: unzip pipeline-scan-LATEST.zip
        - name: Run Pipeline Scanner
        run: java -jar pipeline-scan.jar --verbose --veracode_api_id "${{secrets.VERACODE_API_ID}}" --veracode_api_key "${{secrets.VERACODE_API_KEY}}" --file "webgoat.jar" --fail_on_severity="Very High, High"
